language: go
go:
- '1.8'
jobs:
  include:
    - script: make test
    - stage: Build
      script: make build
    - stage: GitHub Release
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - pubkeyd_ssh_authorized_keys-darwin
          - pubkeyd_ssh_authorized_keys-linux
          - pubkeyd_ssh_authorized_keys.exe
        skip_cleanup: true
        on:
          tags: true
